server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Disable caching in local dev so changes are picked up immediately
    location ~* \.html$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
